### ISSUE TITLE
Cannot reproduce basic Connect User Guide Example 

### ISSUE THREAD

**Issue by mbannert** [rstudio/rsconnect-python#338] opened 2023-01-19 10:47 UTC
I used the rsconnect-python CLI yesterday to deploy an example app to connect. Today, after setting the app a new virtualenv and therefore `pip install rsconnect-python` the basic example was not working any more. A simple 

```sh
rsconnect deploy fastapi -n myServer MyApiPath/
Error: -n/--name cannot be specified in conjunction with options -s/--server
```

caused the above error.  Also leaving out the nickname parameter and caused errors: 

```sh
rsconnect deploy fastapi ./

Internal error: The "" URL scheme is not supported.
```

**Comment by mbannert** [comment] 2023-01-19 11:00
UPDATE: if I replace the nickname (though definitely set and confirmed by running `rsconnect list` with `--server myserver-url.com` it works again...

**Comment by tdstein** [comment] 2023-01-30 16:19
Hi, @mbannert ,

Could you provide me with the URL of the server you linked to `myServer`? If you aren't able to provide the full URL, can you provide the [URL scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes). This is most likely `http` or `https`.

**Comment by tdstein** [comment] 2023-02-13 20:35
Hi again, @mbannert

I have confirmed that the Connect example "FastAPI Stock Pricing Service" works as expected. And I'm unable to reproduce your error.

I am closing this issue. But, if you experience this error again, please reopen this issue (or create a new one).

**Closed by tdstein** 2023-02-13 20:35 UTC
Labels: bug
